### ISSUE TITLE
Brainstorm, how to hide original face attributes

### ISSUE THREAD

**Issue by AidasK** [yingcong/Facelet_Bank#12]
I am training smile model but in every case I can see the old smile. 
Original:
![009296-smiling-s-0 00](https://user-images.githubusercontent.com/2088484/43574085-f30bf4d6-964b-11e8-82a3-af6648f32aed.jpg)

Results with  WF = (QF - PF):
Weight  = 9 (sad)
![009296-smiling-s-9 00](https://user-images.githubusercontent.com/2088484/43577087-934c4bf6-9653-11e8-8693-31cb25cf1850.jpg)

Weight = -12 (smiling)
![009296-smiling-s--12](https://user-images.githubusercontent.com/2088484/43577143-b931be46-9653-11e8-8e52-e4ef011adc00.jpg)

This one is really interesting, because it looks like the smile underneath has changed and the old lips there glued on top of it.  

Results with  WF = (QF - PF) / ((QF - PF) ** 2).mean()

Sad face weight 0.6:
![009296-smiling-s-0 60](https://user-images.githubusercontent.com/2088484/43574094-f68f3a46-964b-11e8-8730-a948da6b7f22.jpg)

Smile face weight -0.4:
![009296-smiling-s--0 40](https://user-images.githubusercontent.com/2088484/43577210-e25a87c6-9653-11e8-94e7-92bc0d6c160c.jpg)

From this I can see that trained model only glues generated lips on top of the original ones. They are not modified. If face is smiling, model is able to add more smile to it (as in Smile face weight -0.4). But anomalies comes out if we need to change attribute to other direction. From smile to sad and vice versa. 

Any thoughts how to make this face sad without these glitches?

**Comment by yingcong** [comment]
I guess the problem may come from the decoder. 
In
https://github.com/yingcong/Facelet_Bank/blob/0f2edb49ea72b4da5da6a12d08cbcd4ff7811f8f/network/decoder.py#L30
I add the original image back in the output of the decoder, so that the decoder can produce higher quality results. But it also makes it more difficult to handle the large changes.
